### PR TITLE
use GOTIFY

### PR DESCRIPTION
**Pull request by mikaelmotin**
added gotify for as a contact service

### CODE REVIEW

**Review by Lee4-M — DISMISSED** [review]
Looks good!

**Review by Lee4-M — COMMENTED** [review]
Fix so that run build works

**Comment by Lee4-M** [comment]
This doesn't work as the environment variable is not exposed when running the check. The workflow needs to be changed to fix this.

**Comment by Oscariremma** [comment]
The current way of accessing the ENV variables is statically on compile time which causes the build failure. What we need to do is read them at runtime which is done by doing [this](https://svelte.dev/docs/kit/$env-dynamic-private)

**Review by Lee4-M — APPROVED** [review]
Looks good

**Pull request merged**
